# Generated by Django 4.1.5 on 2023-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstrueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(default='news', max_length=7),
        ),
    ]
