# Generated by Django 4.1.5 on 2023-02-10 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newstrueapp', '0002_alter_post_type_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersCathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newstrueapp.cathegory')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cathegory',
            name='subscribers',
            field=models.ManyToManyField(through='newstrueapp.SubscribersCathegory', to=settings.AUTH_USER_MODEL),
        ),
    ]
