# Generated by Django 4.1.5 on 2023-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstrueapp', '0005_alter_post_head_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_post',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
