# Generated by Django 4.1.5 on 2023-02-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstrueapp', '0006_alter_post_head_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_post',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
