# Generated by Django 4.1.5 on 2023-02-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstrueapp', '0008_rename_subscriber_subscriberscathegory_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberscathegory',
            old_name='subscribers',
            new_name='subscriber',
        ),
    ]
