# Generated by Django 4.1.5 on 2023-02-19 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstrueapp', '0012_alter_post_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 11, 13, 42, 252335, tzinfo=datetime.timezone.utc)),
        ),
    ]
