# Generated by Django 4.1.5 on 2023-02-19 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newstrueapp', '0014_alter_post_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
